// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chatserver;

namespace chatserver.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20190423213222_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("chatserver.Models.Message", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("message")
                        .IsRequired();

                    b.Property<DateTime>("timestamp");

                    b.Property<string>("user_id")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("chatserver.Models.User", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("avatar");

                    b.Property<DateTime>("created");

                    b.Property<string>("description");

                    b.Property<DateTime>("last_status_change");

                    b.Property<string>("nickname")
                        .IsRequired();

                    b.Property<int>("status");

                    b.Property<DateTime>("updated");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
